version: "3"
services:
  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce
    hostname: gitlab
    ports:
      - 10000:80
    environment:
      GITLAB_OMNIBUS_CONFIG: |
            postgresql['shared_buffers'] = "256MB"
            unicorn['worker_processes'] = 2
            gitlab_rails['initial_root_password'] = "jBCNConf2017"
    volumes:
      - gitlab-data-config:/etc/gitlab
      - gitlab-data-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
    networks:
      stack-ci-network:
  jenkins:
    container_name: jenkins
    build:
      context: ./jenkins
    hostname: jenkins
    ports:
      - 11000:8080
    environment:
      JAVA_OPTS: "-Xmx768m"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
      - "openshift:${DOCKER_HOST_IP}"
    depends_on:
      - gitlab
    networks:
      stack-ci-network:
  nexus:
    container_name: nexus
    image: sonatype/nexus3
    hostname: nexus
    ports:
      - 12000:8081
    environment:
      JAVA_MAX_HEAP: 1024m
    volumes:
      - nexus-data:/nexus-data
      - /etc/timezone:/etc/timezone
    networks:
     stack-ci-network:
  sonarqube:
    container_name: sonarqube
    image: sonarqube
    hostname: sonarqube
    ports:
      - 13000:9000
    environment:
      - JAVA_OPTS=-Xmx768m
    volumes:
      - sonarqube-data:/opt/sonarqube/data
    networks:
      stack-ci-network:
  registry:
    container_name: registry
    image: registry
    hostname: registry
    ports:
      - 5000:5000
    volumes:
      - registry-data:/var/lib/registry
    networks:
      stack-ci-network:
  openshift-origin:
    image: openshift/origin:v1.5.1
    privileged: true
    pid: host
    network_mode: host
    command: start
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/lib/docker:/var/lib/docker:rw
      - /var/lib/origin/openshift.local.volumes:/var/lib/origin/openshift.local.volumes:rslave
networks:
  stack-ci-network:
volumes:
  gitlab-data-config:
  gitlab-data-logs:
  gitlab-data:
  jenkins-data:
  nexus-data:
  sonarqube-data:
  registry-data: